services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.2
    ports:
      - "18123:8123"
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_DATABASE: hass
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    ports:
      - "18124:8123"
    environment:
      - TZ=Etc/UTC
    restart: unless-stopped
