{{- if eq .Values.secret.mode "create" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hass2ch.fullname" . }}
  labels:
    {{- include "hass2ch.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.homeAssistant.token }}
  {{ .Values.secret.hassTokenKey }}: {{ .Values.homeAssistant.token | b64enc | quote }}
  {{- end }}
  {{- if .Values.clickhouse.password }}
  {{ .Values.secret.clickhousePasswordKey }}: {{ .Values.clickhouse.password | b64enc | quote }}
  {{- end }}
{{- end }}