apiVersion: v1
kind: Service
metadata:
  name: {{ include "hass2ch.fullname" . }}
  labels:
    {{- include "hass2ch.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "hass2ch.selectorLabels" . | nindent 4 }}